apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: myeks-blue
  region: ap-northeast-2
  version: "1.29"

# VPC & Subnets
vpc:
  subnets:
    private:
      ap-northeast-2a:
        id: "subnet-0bf67ea47c609e8d8"
      ap-northeast-2c:
        id: "subnet-0419e273f64fccdc0"
  nat:
    gateway: Disable
  clusterEndpoints:
    publicAccess: false
    privateAccess: true

# IAM OIDC & Service Account
iam:
  withOIDC: true
  serviceAccounts:
    - metadata:
        name: aws-load-balancer-controller
        namespace: kube-system
      wellKnownPolicies:
        awsLoadBalancerController: true
    - metadata:
        name: ebs-csi-controller-sa
        namespace: kube-system
      wellKnownPolicies:
        ebsCSIController: true
    - metadata:
        name: efs-csi-controller-sa
        namespace: kube-system
      wellKnownPolicies:
        efsCSIController: true
    - metadata:
        name: cluster-autoscaler
        namespace: kube-system
      wellKnownPolicies:
        autoScaler: true

# Managed Node Groups
managedNodeGroups:
  # On-Demand Instance
  - name: myeks-ng1
    instanceType: t3a.medium
    spot: true
    minSize: 1
    desiredCapacity: 1
    maxSize: 3
    privateNetworking: true
    ssh:
      allow: true
      publicKeyPath: ~/.ssh/id_rsa.pub
    availabilityZones: ["ap-northeast-2a", "ap-northeast-2c"]
    iam:
      withAddonPolicies:
        autoScaler: true
        albIngress: true
        cloudWatch: true
        ebs: true
        efs: true

# Fargate Profiles
fargateProfiles:
  - name: fg-1
    selectors:
    - namespace: dev
      labels:
        env: fargate

# CloudWatch Logging
cloudWatch:
  clusterLogging:
    enableTypes: ["*"]